# Generated by Django 5.1.6 on 2025-05-12 20:14

from django.db import migrations

def create_default_types(apps, schema_editor):
    sale_type_model = apps.get_model('sale_types', 'SaleType')
    sale_types = [
        'Honey',
        'Beeswax',
        'Propolis',
        'Royal Jelly',
        'Pollen',
        'Bee Venom',
        'Nucleus Colonies',
        'Queens',
        'Other'
    ]

    for sale_type in sale_types:
        sale_type_model.objects.get_or_create(name=sale_type)

def reverse_create_default_types(apps, schema_editor):
    sale_type_model = apps.get_model('sale_types', 'SaleType')

    # Delete all types created by this migration
    sale_type_model.objects.filter(name__in=[
        'Honey',
        'Beeswax',
        'Propolis',
        'Royal Jelly',
        'Pollen',
        'Bee Venom',
        'Nucleus Colonies',
        'Queens',
        'Other'
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('sale_types', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_types, reverse_create_default_types),
    ]
