# Generated by Django 5.1.6 on 2025-04-24 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiaries', '0002_alter_apiarymembership_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiaryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='apiaries.apiary')),
            ],
            options={
                'verbose_name': 'apiary note',
                'verbose_name_plural': 'apiary notes',
                'db_table': 'apiary_notes',
                'ordering': ['date'],
            },
        ),
    ]
