# Generated by Django 5.1.6 on 2025-03-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('beekeeper', 'Beekeeper'), ('admin', 'Admin')], default='beekeeper', max_length=20),
        ),
    ]
