# Generated by Django 5.1.6 on 2025-03-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('beekeeper', 'Beekeeper'), ('viewer', 'Viewer'), ('admin', 'Admin')], default='beekeeper', max_length=20),
        ),
    ]
