# Generated by Django 5.1.6 on 2025-03-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_avatar_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
