# Generated by Django 5.1.6 on 2025-06-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('users', '0010_alter_user_managers_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.language', verbose_name='language'),
        ),
    ]
