# Generated by Django 5.1.6 on 2025-06-05 18:54

from django.db import migrations
def create_default_languages(apps, schema_editor):
    language_model = apps.get_model('languages', 'Language')
    languages = [
        {
            'code': 'en',
            'name': 'English',
            'is_active': True,
        },
        {
            'code': 'pl',
            'name': 'Polski',
            'is_active': True,
        },
    ]

    for language in languages:
        language_model.objects.get_or_create(code=language['code'], name=language['name'], is_active=language['is_active'])
        
def reverse_create_default_languages(apps, schema_editor):
    language_model = apps.get_model('languages', 'Language')
    language_model.objects.filter(code__in=['en', 'pl']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_languages, reverse_create_default_languages),
    ]
