# Generated by Django 5.1.6 on 2025-04-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('BEES', 'Bees'), ('BEESWAX', 'Beeswax'), ('FOOD', 'Food'), ('QUEEN', 'Queen'), ('TRANSPORT', 'Transport'), ('UTILITIES', 'Utilities'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
