# Generated by Django 5.1.6 on 2025-04-13 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('coordination_latitude', models.FloatField(blank=True, null=True)),
                ('coordination_longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'apiary',
                'verbose_name_plural': 'apiaries',
                'db_table': 'apiaries',
            },
        ),
        migrations.CreateModel(
            name='ApiaryMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], default='OWNER', max_length=10)),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiaries.apiary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'apiary')},
            },
        ),
        migrations.AddField(
            model_name='apiary',
            name='users',
            field=models.ManyToManyField(related_name='apiaries', through='apiaries.ApiaryMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
