# Generated by Django 5.1.6 on 2025-04-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apiarymembership',
            table='apiaries_membership',
        ),
    ]
