# Generated by Django 5.1.6 on 2025-05-06 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueenNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='queens.queen')),
            ],
            options={
                'verbose_name': 'queen note',
                'verbose_name_plural': 'queen notes',
                'db_table': 'queen_notes',
                'ordering': ['created_at'],
            },
        ),
    ]
