# Generated by Django 5.1.6 on 2025-05-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Harvest Type',
                'verbose_name_plural': 'Harvest Types',
                'db_table': 'harvest_types',
            },
        ),
    ]
