# Generated by Django 5.1.6 on 2025-05-07 20:05

from django.db import migrations


def create_default_types(apps, schema_editor):
    harvest_type_model = apps.get_model('harvest_types', 'HarvestType')

    types = [
        'Honey',
        'Pollen',
        'Propolis',
        'Beeswax',
        'Royal Jelly',
        'Bee Venom',
        'Nectar',
        'Other'
    ]

    # Create default types if they don't exist
    for harvest_type in types:
        harvest_type_model.objects.get_or_create(name=harvest_type)


def reverse_create_default_types(apps, schema_editor):
    harvest_type_model = apps.get_model('harvest_types', 'HarvestType')

    # Delete all types created by this migration
    harvest_type_model.objects.filter(name__in=[
        'Honey',
        'Pollen',
        'Propolis',
        'Beeswax',
        'Royal Jelly',
        'Bee Venom',
        'Nectar',
        'Other'
    ]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('harvest_types', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_types, reverse_create_default_types),
    ]
