version: '3.9'

services:
  db:
    image: postgres:16.7-bullseye
    container_name: apiary-metrics-db
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=apiary_metrics_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
#  web:
#    build: .
#    command: python ./src/manage.py runserver 0.0.0.0:8000
#    depends_on:
#      - db
#    ports:
#      - "8000:8000"
volumes:
  postgres_data: