# Generated by Django 5.1.6 on 2025-05-01 17:46

from django.db import migrations

from apps.queen_types.models import QueenType


def create_default_types(apps, schema_editor):
    queen_type_model = apps.get_model('queen_types', 'QueenType')
    queen_types = [
        'Italian',
        'Carniolan',
        'Caucasian',
        'Buckfast',
        'Russian',
        'Cordovan',
        'Mongolian',
        'Other'
    ]

    for queen_type in queen_types:
        queen_type_model.objects.get_or_create(name=queen_type)


def reverse_create_default_types(apps, schema_editor):
    queen_type_model = apps.get_model('queen_types', 'QueenType')

    # Delete all types created by this migration
    queen_type_model.objects.filter(name__in=[
        'Italian',
        'Carniolan',
        'Caucasian',
        'Buckfast',
        'Russian',
        'Cordovan',
        'Mongolian',
        'Other'
    ]).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('queen_types', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_types, reverse_create_default_types),
    ]
