# Generated by Django 5.1.6 on 2025-04-28 16:20

import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hives', '0003_hive_aggression_hive_strength'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('type', utils.fields.LowerCaseField(default='other', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queens', to='hives.hive')),
            ],
            options={
                'verbose_name': 'queen',
                'verbose_name_plural': 'queens',
                'db_table': 'queens',
                'ordering': ['-date'],
            },
        ),
    ]
