# Generated by Django 5.1.6 on 2025-04-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hives', '0003_hive_aggression_hive_strength'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiveInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='hives.hive')),
            ],
            options={
                'verbose_name': 'hive inspection',
                'verbose_name_plural': 'hive inspections',
                'db_table': 'hive_inspections',
                'ordering': ['date'],
            },
        ),
    ]
