# Generated by Django 5.1.6 on 2025-04-16 19:09

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='type',
            field=utils.fields.LowerCaseField(default='other', max_length=255),
        ),
    ]
