# Generated by Django 5.1.6 on 2025-04-16 17:16

from django.db import migrations


def create_default_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('expense_categories', 'ExpenseCategory')

    categories = [
        'bees',
        'beeswax',
        'food',
        'queen',
        'transport',
        'utilities',
        'other'
    ]

    # Create default categories if they don't exist
    for category in categories:
        ExpenseCategory.objects.get_or_create(name=category)


def reverse_create_default_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('expense_categories', 'ExpenseCategory')

    # Delete all categories created by this migration
    ExpenseCategory.objects.filter(name__in=[
        'bees',
        'beeswax',
        'food',
        'queen',
        'transport',
        'utilities',
        'other'
    ]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('expense_categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_create_default_categories),
    ]
